<?php
// download_batch_pdf.php - Vehicle Sampark Physical QR Tag Sheet PDF Exporter

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/includes/functions.php';
require_once __DIR__ . '/includes/tag_template.php';

use Dompdf\Dompdf;
use Dompdf\Options;

ini_set('memory_limit', '512M');
set_time_limit(300);

$batchId = isset($_GET['batch_id']) ? (int)$_GET['batch_id'] : 0;

if ($batchId <= 0) {
    die("Error: Invalid Batch ID.");
}

$stmt = $pdo->prepare("SELECT * FROM batches WHERE id = ?");
$stmt->execute([$batchId]);
$batch = $stmt->fetch();

if (!$batch) {
    die("Error: Batch not found.");
}

$codeStmt = $pdo->prepare("SELECT * FROM qr_codes WHERE batch_id = ? ORDER BY id ASC");
$codeStmt->execute([$batchId]);
$qrCodes = $codeStmt->fetchAll();

if (empty($qrCodes)) {
    die("Error: No QR codes found for this batch.");
}

// Generate Printable Physical Tag Cards for PDF Sheet
$tagsHtml = '';
foreach ($qrCodes as $index => $qr) {
    $tagsHtml .= '
        <div class="sheet-tag-item">
            ' . renderVehicleSamparkTagHTML($qr['code_number'], $batch['form_title']) . '
        </div>
    ';
}

$html = '
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Vehicle Sampark QR Tag Sheet - ' . htmlspecialchars($batch['batch_name']) . '</title>
    <style>
        @page { margin: 15px; }
        body { font-family: Helvetica, Arial, sans-serif; color: #0f172a; margin: 0; padding: 10px; background: #ffffff; }
        
        .sheet-header { border-bottom: 2px solid #f97316; padding-bottom: 8px; margin-bottom: 12px; }
        .sheet-title { font-size: 16px; font-weight: bold; color: #000000; margin: 0; }
        .sheet-subtitle { font-size: 10px; color: #f97316; font-weight: bold; margin-top: 2px; text-transform: uppercase; }

        .sheet-tag-item {
            page-break-inside: avoid;
            margin-bottom: 15px;
        }

        ' . getVehicleSamparkTagCSS() . '

        .footer { margin-top: 15px; font-size: 8px; color: #64748b; text-align: center; border-top: 1px solid #cbd5e1; padding-top: 8px; }
    </style>
</head>
<body>
    <div class="sheet-header">
        <div class="sheet-title">VEHICLE SAMPARK &bull; Printable Vehicle Tag Sheet</div>
        <div class="sheet-subtitle">' . htmlspecialchars($batch['form_title']) . ' (' . htmlspecialchars($batch['batch_name']) . ') &bull; Total: ' . count($qrCodes) . ' Physical Tags</div>
    </div>

    <div class="sheet-container">
        ' . $tagsHtml . '
    </div>

    <div class="footer">
        Generated by Vehicle Sampark Engine &bull; Total Included Tags: ' . count($qrCodes) . ' &bull; Visit VEHICLESAMPARK.COM
    </div>
</body>
</html>
';

$options = new Options();
$options->set('isRemoteEnabled', true);
$options->set('defaultFont', 'Helvetica');

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

$filename = "VehicleSampark_TagSheet_" . $batchId . ".pdf";
$dompdf->stream($filename, ["Attachment" => true]);
