<?php
// download_pdf.php - Vehicle Sampark Individual Response PDF Report with Physical Tag Header

require_once __DIR__ . '/vendor/autoload.php';
require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/includes/functions.php';
require_once __DIR__ . '/includes/tag_template.php';

use Dompdf\Dompdf;
use Dompdf\Options;

$codeNumber = sanitize($_GET['code'] ?? '');

if (empty($codeNumber)) {
    die("Error: No QR Code specified.");
}

$stmt = $pdo->prepare("
    SELECT q.*, b.form_title, b.batch_name
    FROM qr_codes q
    JOIN batches b ON q.batch_id = b.id
    WHERE q.code_number = ?
");
$stmt->execute([$codeNumber]);
$qr = $stmt->fetch();

if (!$qr) {
    die("Error: QR Code not found.");
}

if ($qr['status'] !== 'submitted') {
    die("Error: Form details have not been submitted for this QR Code yet.");
}

$subStmt = $pdo->prepare("SELECT * FROM submissions WHERE qr_code_id = ? ORDER BY id DESC LIMIT 1");
$subStmt->execute([$qr['id']]);
$submission = $subStmt->fetch();

if (!$submission) {
    die("Error: Submission details missing.");
}

$responses = json_decode($submission['response_data'], true) ?: [];

// Build Form Responses Table
$rowsHtml = '';
foreach ($responses as $label => $val) {
    $displayVal = htmlspecialchars($val);

    if (typeof_image($val) && file_exists(__DIR__ . '/' . $val)) {
        $imgType = pathinfo($val, PATHINFO_EXTENSION);
        $imgData = file_get_contents(__DIR__ . '/' . $val);
        $base64Src = 'data:image/' . $imgType . ';base64,' . base64_encode($imgData);
        $displayVal = '<br><img src="' . $base64Src . '" style="max-width: 220px; max-height: 220px; margin-top: 5px; border-radius: 6px; border: 1px solid #ccc;">';
    } elseif (is_string($val) && (str_starts_with($val, 'uploads/'))) {
        $displayVal = 'Uploaded Document: ' . htmlspecialchars(basename($val));
    }

    $rowsHtml .= '
        <tr>
            <td class="label-td">' . htmlspecialchars($label) . '</td>
            <td class="value-td">' . $displayVal . '</td>
        </tr>
    ';
}

function typeof_image($path) {
    if (!is_string($path)) return false;
    return (bool)preg_match('/\.(jpg|jpeg|png|gif|webp)$/i', $path);
}

// Render Physical Vehicle Sampark Tag Sticker Card Header
$tagStickerHtml = renderVehicleSamparkTagHTML($codeNumber, $qr['form_title']);

$html = '
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Vehicle Sampark Report - ' . htmlspecialchars($codeNumber) . '</title>
    <style>
        body { font-family: Helvetica, Arial, sans-serif; color: #1e293b; margin: 0; padding: 15px; font-size: 12px; line-height: 1.4; background: #ffffff; }
        
        .tag-container-wrap { margin-bottom: 20px; text-align: center; }

        .meta-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 10px 14px; margin-bottom: 20px; border-left: 4px solid #f97316; }
        .meta-card table { width: 100%; font-size: 11px; }
        .meta-label { color: #64748b; font-weight: bold; }
        .meta-val { color: #0f172a; }
        
        .data-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        .data-table th { background: #000000; color: #ffffff; text-align: left; padding: 9px 12px; font-size: 11px; text-transform: uppercase; border-bottom: 2px solid #f97316; }
        .data-table td { padding: 10px 12px; border-bottom: 1px solid #e2e8f0; vertical-align: top; }
        .label-td { width: 35%; font-weight: bold; color: #334155; background: #f8fafc; }
        .value-td { width: 65%; color: #0f172a; }
        
        ' . getVehicleSamparkTagCSS() . '

        .footer { margin-top: 30px; border-top: 1px solid #cbd5e1; padding-top: 12px; font-size: 9px; color: #94a3b8; text-align: center; }
    </style>
</head>
<body>
    <div class="tag-container-wrap">
        ' . $tagStickerHtml . '
    </div>

    <div class="meta-card">
        <table>
            <tr>
                <td><span class="meta-label">Registration Date:</span> <span class="meta-val">' . date('F j, Y, g:i a', strtotime($submission['submitted_at'])) . '</span></td>
                <td><span class="meta-label">Status:</span> <span class="meta-val" style="color: #10b981; font-weight: bold;">Registered & Active</span></td>
                <td><span class="meta-label">Serial Tag #:</span> <span class="meta-val" style="font-family: monospace; font-weight: bold;">' . htmlspecialchars($codeNumber) . '</span></td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th>Registered Vehicle & Owner Field</th>
                <th>Submitted Details</th>
            </tr>
        </thead>
        <tbody>
            ' . $rowsHtml . '
        </tbody>
    </table>

    <div class="footer">
        Generated by Vehicle Sampark Engine &bull; Physical Tag Identifier: ' . htmlspecialchars($codeNumber) . ' &bull; ' . date('Y-m-d H:i:s') . '
    </div>
</body>
</html>
';

$options = new Options();
$options->set('isRemoteEnabled', true);
$options->set('defaultFont', 'Helvetica');

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

$dompdf->stream("VehicleSampark_TagReport_" . $codeNumber . ".pdf", ["Attachment" => true]);
